extends Node

enum Type {
    NEUTRAL,
    WATER,
    PLANT,
    FIRE,
}

enum BattleState {
    ENTER_BATTLE,
    PLAYER_CHOOSES_CHARACTER_ACTION,
    PLAYER_CHOOSES_CREATURE_ACTION,
    WAITING_FOR_OTHER_PLAYER,
    ACTIONS_RESOLUTION,
    PLAYER_LOST_CREATURE,
    RECEIVE_ROUND_REWARDS,
    BATTLE_REPORT,
    BATTLE_REWARDS,
}

enum CharacterAction {
    COMMAND_CREATURE,
    CHANGE_CREATURE,
    MOVE,
    FOLLOW,
}
